global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-service:8001']

  - job_name: 'training-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['training-service:8002']

  - job_name: 'reference-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['reference-service:8003']

  - job_name: 'notes-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['notes-service:8004']