global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:80']
    metrics_path: /health

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']
    metrics_path: /health

  - job_name: 'training-service'
    static_configs:
      - targets: ['training-service:8002']
    metrics_path: /health

  - job_name: 'reference-service'
    static_configs:
      - targets: ['reference-service:8003']
    metrics_path: /health

  - job_name: 'notes-service'
    static_configs:
      - targets: ['notes-service:8004']
    metrics_path: /health

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']