name: Автодеплой

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Деплой
    runs-on: self-hosted
    
    steps:
      - name: Копирование кода
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Подготовка директории
        run: |
          sudo mkdir -p /var/www/apps/rangerookies
          sudo chown -R $USER:$USER /var/www/apps/rangerookies
          rsync -av --delete ./ /var/www/apps/rangerookies/

      - name: Создание переменных окружения
        run: |
          cd /var/www/apps/rangerookies
          echo "${{ secrets.AUTH_ENV }}" > auth-service/.env
          echo "${{ secrets.TRAINING_ENV }}" > training-service/.env
          echo "${{ secrets.REFERENCE_ENV }}" > reference-service/.env
          echo "${{ secrets.NOTES_ENV }}" > notes-service/.env

      - name: Остановка старых контейнеров
        run: |
          cd /var/www/apps/rangerookies
          docker-compose down --remove-orphans

      - name: Сборка и запуск
        run: |
          cd /var/www/apps/rangerookies
          echo "Сборка образов..."
          docker-compose build
          
          echo "Запуск всех сервисов..."
          docker-compose up -d
          
          echo "Ожидание готовности всех сервисов..."
          timeout 600 bash -c '
            while docker-compose ps | grep -q "unhealthy\|starting"; do
              echo "Некоторые сервисы еще не готовы, ждем..."
              sleep 30
            done
            echo "Все сервисы готовы!"
            docker-compose ps
          '

      - name: Проверка деплоя
        run: |
          cd /var/www/apps/rangerookies
          echo "Проверка деплоя..."
          docker-compose ps
          
          unhealthy_count=$(docker-compose ps | grep -c "unhealthy" || true)
          if [ "$unhealthy_count" -gt 0 ]; then
            echo "Найдено $unhealthy_count неготовых сервисов"
            docker-compose logs --tail=50
            exit 1
          fi
          
          echo "Все сервисы готовы и работают!" 